### PR TITLE
Fix padding

### PR DESCRIPTION
**Pull request by j-hui**
thanks to u/Fleinsopp for suggesting this fix (:

### CODE REVIEW

**Comment by Lopi-py** [comment]
hey, cool, try to use lua "native" functions 
```lua
local function subtab(s)
  return s:gsub("\t", "  ")
end
```
and
```lua
local strlen = string.len
-- or just
#s
```

**Comment by j-hui** [comment]
@Lopi-py why do you suggest using Lua functions?

`string.sub` operates over byte indices, meaning the behavior will likely be different when handling non-ASCII characters. 

For my own understanding: is there any advantage to using Lua's `string.gsub` over Vim's substitution?

**Comment by Lopi-py** [comment]
oh, you're right
image
image
what about string.gsub?, is there any advantage of `vim.fn.substitute` over `string.gsub`?

**Comment by j-hui** [comment]
Point taken, though I won't be convinced about any substantive performance gains without some profiling. I switched to `gsub` since it's at least more idiomatic.

**Pull request merged**
