### PR TITLE
Fix error `E322` and `E315` on exit

### LINKED ISSUE #101: Error on Exit in nvim-0.8
Hello!  Thanks for the plugin. 

This is very similar to https://github.com/j-hui/fidget.nvim/issues/4 but I'm just now seeing this after updating neovim to `NVIM v0.8.0-dev-1128-g62db91f06` on MacOS 12.5.1 M1 / arm. 

```
Error executing vim.schedule lua callback: .../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:90: Error occured:
.../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:289: Vim:E322: line number out of range: 1 past the end
stack traceback:
        [C]: in function 'error'
        .../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:90: in function 'render_fidgets'
        .../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:222: in function 'fmt'
        .../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:329: in function 'do_spin'
        .../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:350: in function 'spin'
        .../warwil2/.config/nvim/plugged/fidget.nvim/lua/fidget.lua:341: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

It has no impact on the functionality of neovim of your plugin

Thanks

### LINKED ISSUE #105: Bug on exit with neovim 8.0 stable
Fidget errors out when exiting neovim while fidget is still showing progress. If fidget finishes showing everything and now isn't being seen in the window, no errors, but you try to exit while fidget is being seen in the window, it spits out the following error:
```lua
Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:91: Error occured:
...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:291: Vim:E315: ml_get: invalid lnum: 2
stack traceback:
	[C]: in function 'error'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:91: in function 'render_fidgets'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:223: in function 'fmt'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:331: in function 'do_spin'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:352: in function 'spin'
	...are/nvim/site/pack/packer/opt/fidget.nvim/lua/fidget.lua:343: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>⏎ 
```

### PR DESCRIPTION
**Pull request by FWFWLL**
This PR implements the "fix" suggested here https://github.com/j-hui/fidget.nvim/issues/101#issuecomment-1264522143

Fixes #105
Fixes #101

### CODE REVIEW

**Comment by lewis6991** [comment]
@j-hui are you able merge this please?

**Comment by joeyschoblaska** [comment]
Confirmed that this seems to fix the issue on my M1 Mac.

**Comment by jinzhongjia** [comment]
I'm still waiting for this pr to be merged, once it's merged I can move from lsp-progross， this plugin is awesome

**Comment by ateijelo** [comment]
Until this is merged, you can use the PR's commit directly; e.g. with Packer:
```
use { "FWFWLL/fidget.nvim", commit = "30e846ae571c268f9ca74b8e95e7f5930191ef4c" }
```

**Comment by j-hui** [comment]
Sorry for the delay everyone, and thanks for your patience! I just tested this and will merge it now.

**Pull request merged**
