### PR TITLE
fix: right-justify by padding with spaces in Lua, rather than using :right

### PR DESCRIPTION
**Pull request by 0xAdk**
I was testing to see if this fixed the highlights and noticed it fixed the scrolloff issue (and possibly other unknown issues?)

### CODE REVIEW

**Comment by 0xAdk** [comment]
is there a good reason to make the code more complicated by having to cache the offsets?

**Comment by j-hui** [comment]
I adjusted the PR to add the padding in `window.lua` instead of `view.lua`. I still need to document this somewhere sometime, but I want `view.lua` to still only be concerned with the "abstract view" of the buffer contents.

Also, I think your commit assumed that the `highlights` array is indexed by line numbers, but it is not; each element of the `highlights` array is a separate call to `nvim_buf_add_highlight()`, but multiple highlights may be applied to the same line (and some lines may have no highlights at all). Those are not cached offsets; I'm keeping them as a layer of indirection so that we can resolve the offset for each line while we iterate through the `highlights` array.

This PR now essentially reverts #155, while also fixing the problem it poses (and also raised in #156).

**Comment by j-hui** [comment]
This PR now fixes the issue for me entirely (even with the minimal init script, and with `scrolloff` set to to some non-zero number); let me know if you still have any problems on your end

**Comment by 0xAdk** [comment]
yep both issues are fixed!

**Comment by 0xAdk** [comment]
I assume word changing color has semantic meaning and isn't a bug?

**Comment by j-hui** [comment]
Awesome!

And yeah, the changing color indicates in progress VS complete.

It's because of this: https://github.com/j-hui/fidget.nvim/blob/b8ec74a031febd52f64559b15002d5dee08e4791/lua/fidget/progress.lua#L120

If you want it to be the same color, set `progress.display.done_style` and `progress.display.progress_style` to the same style.

**Comment by j-hui** [comment]
But yeah thanks for spotting this issue with using `:right` and getting started on this PR!

**Comment by 0xAdk** [comment]
np! 

Flipping the line order also seems pretty easy to do (and would be the last thing I want to get by to how legacy fidget worked) but I'm not really sure where it would fit in the model you have setup (in set lines based on what you said?) or how to go about it without messing with the table since you have a comment about caching the results (a simple vim.iter(table):rev():totable() would do the trick)

**Pull request merged**
