### PR TITLE
fix: scrolloff breaks notification window

### PR DESCRIPTION
**Pull request by 0xAdk**
I have scrolloff set to 5, which seems to break the notification window

image

(the colors are also broken, but that's a separate issue)

### CODE REVIEW

**Comment by j-hui** [comment]
Hmm that's odd, I also have `set scrolloff=5` in my config and I don't have this issue.

I pushed a change to use the existing `win_set_local_options()` helper (from #77) instead of `vim.wo`, for the sake of being consistent. Can you let me know if it still fixes the issue for you?

**Comment by 0xAdk** [comment]
yep still fixed, though if it's not happening for you then that might not be the root cause.

My colors are also messed up, which isn't fixed by this, so I'm going to try and isolate if another plugin is causing this.

**Comment by 0xAdk** [comment]
btw I should mention I'm on the latest version of nightly

**Comment by j-hui** [comment]
I'm unable to reproduce the highlighting issue on my end using a nightly build, but can you open a separate issue for it with a screenshot of how things look now?

**Pull request merged**
