### PR TITLE
Show fidgets only if buf has lsp client attached, fix #5

### LINKED ISSUE #5: Weird window behaviour
https://gyazo.com/c8d1cdd0c0c9dff66f583b448c8d3697
When I open NvimTree the floating progress does not keep in the window and goes to NvimTree window.

### PR DESCRIPTION
**Pull request by j-hui**
Fix #5, potentially address #13 and #10 (though does not directly implement suggestions)

### CODE REVIEW

**Comment by wookayin** [comment]
I have a NvimTree buffer which has no clients attached:

:LspInfo
```
 Language client log: $HOME.cache/nvim/lsp.log
 Detected filetype:   NvimTree
 
 0 client(s) attached to this buffer: 
 
 2 active client(s) not attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [1, 13])
 ...
 
 Client: pyright (id: 2, pid: 66277, bufnr: [1, 13])
 ...

```

But it shows the fidget when you open a new python buffer (or anything else that has LSP client attached) and move the cursor to the nvimtree buffer, for instance.

**Comment by j-hui** [comment]
@wookayin are you testing that with this branch checked out?

I just set up NvimTree and don't see this issue.

**Comment by wookayin** [comment]
@j-hui My bad, never mind. After checking out the correct commit, it works fine. 

But I think this one was supposed to be a fix like messages from **only relevant** (i.e., attached) LSP clients should be shown? For example, if you have `a.py` and `b.lua`, then LSP messages from sumneko-lua should not appear in the python window.

**Comment by j-hui** [comment]
No problem. There's still a problem now that the messages basically stay frozen after switching focus to an irrelevant buffer, but at least it doesn't display where it isn't supposed to. I'll fix that once I've decided what the right behavior should be.

**Comment by j-hui** [comment]
Oops, didn't mean to force push that but I had bungled a rebase xD

In any case, I fixed the frozen fidget issue too. I'm going to test drive this tonight and will merge it if I don't encounter any issues.

**Comment by Lopi-py** [comment]
This fixes #4 for me

**Comment by wookayin** [comment]
Thanks!

**Pull request merged**
